let cfg;
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json'},...opt});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||r.statusText);return j}
async function load(){cfg=await api('/api/config');render();refreshStatus();setInterval(refreshStatus,3000)}
function render(){renderSources();renderTargets();$('#raw').value=JSON.stringify(cfg,null,2)}
function renderSources(){const box=$('#sources');box.innerHTML='';cfg.sources.forEach((s,i)=>{const d=document.createElement('div');d.className='item';d.innerHTML=`<div class="item-head"><b>${esc(s.name||s.id)}</b><div><button data-run>立即测速</button> <button data-del class="danger">删除</button></div></div><div class="row">
<label class="f3">ID<input data-k="id" value="${esc(s.id)}"></label><label class="f3">名称<input data-k="name" value="${esc(s.name)}"></label><label class="f2">协议<select data-k="family"><option ${s.family==='ipv4'?'selected':''}>ipv4</option><option ${s.family==='ipv6'?'selected':''}>ipv6</option></select></label><label class="f2">周期(分钟)<input type="number" data-k="interval_minutes" value="${s.interval_minutes||0}"></label><label class="f2">启用<select data-k="enabled"><option value="true" ${s.enabled?'selected':''}>是</option><option value="false" ${!s.enabled?'selected':''}>否</option></select></label>
<label class="f12">IP 源（每行一个：URL / 文件 / CIDR / IP）<textarea data-inputs>${esc((s.inputs||[]).join('\n'))}</textarea></label>
<label class="f3">测速 URL<input data-c="url" value="${esc(s.cfst?.url||'')}"></label><label class="f2">最低速度 MB/s<input type="number" step="0.1" data-c="speed_min_mb" value="${s.cfst?.speed_min_mb||0}"></label><label class="f2">延迟上限 ms<input type="number" data-c="latency_max_ms" value="${s.cfst?.latency_max_ms||0}"></label><label class="f2">丢包上限 0-1<input type="number" step="0.01" data-c="loss_max" value="${s.cfst?.loss_max||0}"></label><label class="f3">Colo（逗号）<input data-colo value="${esc((s.cfst?.colo||[]).join(','))}" placeholder="NRT,HKG"></label>
</div>`;bindSource(d,s,i);box.appendChild(d)})}
function bindSource(d,s,i){d.querySelectorAll('[data-k]').forEach(el=>el.onchange=()=>{let v=el.value;if(el.dataset.k==='enabled')v=v==='true';if(el.type==='number')v=Number(v);s[el.dataset.k]=v;renderTargets();syncRaw()});d.querySelector('[data-inputs]').onchange=e=>{s.inputs=e.target.value.split(/\n+/).map(x=>x.trim()).filter(Boolean);syncRaw()};d.querySelectorAll('[data-c]').forEach(el=>el.onchange=()=>{s.cfst=s.cfst||{};s.cfst[el.dataset.c]=el.type==='number'?Number(el.value):el.value;syncRaw()});d.querySelector('[data-colo]').onchange=e=>{s.cfst.colo=e.target.value.split(',').map(x=>x.trim().toUpperCase()).filter(Boolean);syncRaw()};d.querySelector('[data-run]').onclick=async()=>{await api('/api/run/source?id='+encodeURIComponent(s.id),{method:'POST'});refreshStatus()};d.querySelector('[data-del]').onclick=()=>{cfg.sources.splice(i,1);cfg.targets.forEach(t=>t.sources=(t.sources||[]).filter(r=>r.source_id!==s.id));render();}}
function renderTargets(){const box=$('#targets');box.innerHTML='';cfg.targets.forEach((t,i)=>{const opts=cfg.sources.map(s=>`<option value="${esc(s.id)}">${esc(s.name||s.id)} (${s.family})</option>`).join('');const refs=(t.sources||[]).map((r,ri)=>`<div class="ref"><select data-ref-source="${ri}">${opts.replace(`value="${esc(r.source_id)}"`,`value="${esc(r.source_id)}" selected`)}</select><input type="number" min="1" data-ref-count="${ri}" value="${r.count||1}"><button data-ref-del="${ri}">×</button></div>`).join('');const d=document.createElement('div');d.className='item';d.innerHTML=`<div class="item-head"><b>${esc(t.name||t.hostname||t.id)}</b><div><button data-sync>同步 DNS</button> <button data-del class="danger">删除</button></div></div><div class="row"><label class="f3">ID<input data-k="id" value="${esc(t.id)}"></label><label class="f3">名称<input data-k="name" value="${esc(t.name)}"></label><label class="f4">Hostname<input data-k="hostname" value="${esc(t.hostname)}"></label><label class="f2">启用<select data-k="enabled"><option value="true" ${t.enabled?'selected':''}>是</option><option value="false" ${!t.enabled?'selected':''}>否</option></select></label><div class="f12"><span class="muted">引用 IP 池（同一 hostname 可同时引用 IPv4 + IPv6，自动写 A + AAAA）</span>${refs}<button data-add-ref>+ 引用 IP 池</button></div></div>`;bindTarget(d,t,i);box.appendChild(d)})}
function bindTarget(d,t,i){d.querySelectorAll('[data-k]').forEach(el=>el.onchange=()=>{t[el.dataset.k]=el.dataset.k==='enabled'?el.value==='true':el.value;syncRaw()});d.querySelectorAll('[data-ref-source]').forEach(el=>el.onchange=()=>{t.sources[Number(el.dataset.refSource)].source_id=el.value;syncRaw()});d.querySelectorAll('[data-ref-count]').forEach(el=>el.onchange=()=>{t.sources[Number(el.dataset.refCount)].count=Number(el.value);syncRaw()});d.querySelectorAll('[data-ref-del]').forEach(el=>el.onclick=()=>{t.sources.splice(Number(el.dataset.refDel),1);renderTargets();syncRaw()});d.querySelector('[data-add-ref]').onclick=()=>{if(!cfg.sources.length)return;t.sources=t.sources||[];t.sources.push({source_id:cfg.sources[0].id,count:5});renderTargets();syncRaw()};d.querySelector('[data-sync]').onclick=async()=>{try{await api('/api/sync/target?id='+encodeURIComponent(t.id),{method:'POST'})}catch(e){alert(e.message)}refreshStatus()};d.querySelector('[data-del]').onclick=()=>{cfg.targets.splice(i,1);render();}}
function syncRaw(){$('#raw').value=JSON.stringify(cfg,null,2)}
async function refreshStatus(){const s=await api('/api/status');const box=$('#status');box.innerHTML='';for(const src of cfg.sources){const st=s.sources[src.id]||{};const d=document.createElement('div');d.className='card';d.innerHTML=`<b>${esc(src.name||src.id)}</b><div class="muted">${esc(st.stage||'尚未运行')}</div><div>${st.running?'<span class="pill">运行中</span>':''}<span class="pill">结果 ${st.results?.length||0}</span></div>${st.error?`<div class="bad">${esc(st.error)}</div>`:''}`;box.appendChild(d)}for(const t of cfg.targets){const st=s.targets[t.id];const d=document.createElement('div');d.className='card';d.innerHTML=`<b>${esc(t.hostname)}</b><div class="muted">DNS Target</div>${st?`<div class="${st.ok?'ok':'bad'}">${st.ok?'最近同步成功':esc(st.error||'同步失败')}</div>`:'<div class="muted">尚未同步</div>'}`;box.appendChild(d)}}
$('#save').onclick=async()=>{try{await api('/api/config',{method:'PUT',body:JSON.stringify(cfg)});alert('配置已保存')}catch(e){alert(e.message)}};$('#runAll').onclick=()=>api('/api/run/all',{method:'POST'});$('#applyRaw').onclick=()=>{try{cfg=JSON.parse($('#raw').value);render()}catch(e){alert(e.message)}};$('#addSource').onclick=()=>{cfg.sources.push({id:'source-'+Date.now(),name:'新 IP 池',enabled:true,family:'ipv4',inputs:[],interval_minutes:360,keep_results:50,cfst:{binary:'cfst',port:443,threads:4,ping_count:200,download_count:10,download_time:10,latency_max_ms:200,latency_min_ms:0,loss_max:0.2,speed_min_mb:5,httping:true,colo:[],all_ip:false}});render()};$('#addTarget').onclick=()=>{cfg.targets.push({id:'target-'+Date.now(),name:'新域名',enabled:true,provider_id:cfg.providers[0]?.id||'',hostname:'',ttl:60,proxied:false,sources:[]});render()};load();
